### PR TITLE
Adding myself to webring!

### PR DESCRIPTION
**Pull request by alexanderjalexander**

### CODE REVIEW

**Comment by ezrizhu** [comment]
Please add the webring at the footer of the page that you're linking.

**Comment by alexanderjalexander** [comment]
Done! I have it as a separate TypeScript function within my website at the moment. I have my UserID put in as well as various variables, but in the event of API errors it returns an empty div. I put in a dummy username for now on my dev branch and this is what it shows
image

**Comment by ezrizhu** [comment]
thank you, welcome to the ring.

**Comment by alexanderjalexander** [comment]
thank you thank you! :D

**Pull request merged**
